language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
script: python setup.py nosetests --with-coverage --cover-package=xcmd
after_success:
  coveralls
